# Generated by Django 5.1.4 on 2025-01-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='names',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
