# Generated by Django 5.1.4 on 2025-01-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_room_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='names',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
